/* Build the clean-URL copies GitHub Pages serves.
 *
 * The .dc.html files at the root are the sources (open them for editing). This script copies each
 * one to <route>/index.html so the site answers at shifu.health/, /nutrition, /exercise, /coverage,
 * /manifesto and /goals/<slug>. Sources use root-absolute paths (/support.js, /assets/...) and the
 * clean routes for links, so the copies work unchanged apart from a canonical tag.
 *
 * Usage: node build-routes.mjs   (run after editing any page, before committing)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ORIGIN = 'https://shifu.health';

export const GOALS = ['lower-blood-pressure', 'glp-1-guidance', 'managing-diabetes', 'losing-10-pounds', 'building-strength', 'a-half-marathon', 'eating-well-on-a-budget', 'recovering-from-an-injury', 'cutting-sugar', 'sleeping-better', 'moving-more', 'gut-health'];

export const ROUTES = {
  '/': 'Bespoke Healthcare v3.dc.html',
  '/nutrition': 'Bespoke Nutrition v3.dc.html',
  '/exercise': 'Bespoke Exercise v3.dc.html',
  '/coverage': 'Coverage.dc.html',
  '/manifesto': 'Manifesto.dc.html',
  '/logo-ideas': 'Logo Ideas.dc.html',
  '/legal': 'Legal.dc.html',
  ...Object.fromEntries(['privacy', 'terms', 'eula', 'subscription', 'open-source'].map((s) => ['/legal/' + s, 'Legal - ' + s + '.dc.html'])),
  ...Object.fromEntries(GOALS.map((s) => ['/goals/' + s, 'Goal - ' + s + '.dc.html'])),
};

// Cloudflare caches static assets for hours, so every copy references scripts and styles with a
// content-hash query; a changed file gets a new URL and phones pick it up on the next load.
const ASSETS = ['shifu-team.js', 'support.js', 'start-modal.js', 'strip.js', 'site-nav.js', 'profile-modal.js', 'image-slot.js', 'mobile.css'];
const assetVersion = Object.fromEntries(ASSETS.map((f) => [f, createHash('sha1').update(readFileSync(join(HERE, f))).digest('hex').slice(0, 8)]));
const stamp = (html) => ASSETS.reduce((h, f) => h.split('"/' + f + '"').join('"/' + f + '?v=' + assetVersion[f] + '"'), html);

let n = 0;
for (const [route, file] of Object.entries(ROUTES)) {
  let html = readFileSync(join(HERE, file), 'utf8');
  const canonical = `<link rel="canonical" href="${ORIGIN}${route === '/' ? '/' : route + '/'}">`;
  html = html.replace('<meta name="viewport" content="width=device-width, initial-scale=1">', `<meta name="viewport" content="width=device-width, initial-scale=1">\n${canonical}`);
  if (!html.includes(canonical)) throw new Error(file + ': viewport meta not found');
  const outDir = route === '/' ? HERE : join(HERE, route.slice(1));
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'index.html'), '<!-- GENERATED by build-routes.mjs from "' + file + '" - edit the source, then rerun the build. -->\n' + stamp(html));
  n++;
}
console.log(`built ${n} routes`);
