/* Regenerate shifu-team.js, team.json and assets/team/.
 *
 * Names, photos, full bios, education, credentials, licensing and links come verbatim from
 * the live site's roster (~/shifu-website/public/team/team-data.js). team-overlay.json adds
 * only the fields the marketing site needs on top: which discipline a person is filed under,
 * the one-line credential and license strings shown on a card, a short card bio, and the
 * Coverage topics they handle.
 *
 * Photos are copied into assets/team/ so the design files work when served from this folder
 * (the README asks for every hot-linked asset to be self-hosted). Profile URLs point at the
 * live profile pages on shifu.health.
 *
 * Usage: node gen-team.mjs
 */
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const SITE_ROOT = '/Users/spencertate4/shifu-website/public';
const SOURCE = join(SITE_ROOT, 'team/team-data.js');
const LIVE_ORIGIN = 'https://shifu.health';
const HERE = dirname(fileURLToPath(import.meta.url));
const PHOTO_DIR = join(HERE, 'assets/team');

const require = createRequire(import.meta.url);
global.window = {};
require(SOURCE);
const roster = new Map(global.window.SHIFU_TEAM.map((m) => [m.slug, m]));

const overlay = JSON.parse(readFileSync(join(HERE, 'team-overlay.json'), 'utf8'));

const ORDER = ['n', 'e', 'a', 'f', 'i'];
const HEADING = { n: 'Nutrition', e: 'Exercise', a: 'Clinical advisors (internal consultants, not bookable)', f: 'Founding team (from shifu.health/about; data in team-overlay.json "person")', i: 'Investors' };

// People who are not in the live care-team roster (the founders, from shifu.health/about) carry their
// full record under "person" in team-overlay.json instead.
const missing = Object.keys(overlay).filter((id) => !roster.has(id) && !overlay[id].person);
if (missing.length) throw new Error('not in the live roster: ' + missing.join(', '));


// Cards never show a photo larger than ~300px, so cap the copies at 640px (macOS sips) to keep the folder small.
function shrink(path) {
  try { execFileSync('sips', ['-Z', '640', path], { stdio: 'ignore' }); } catch (e) { /* not on macOS: keep the original */ }
}

mkdirSync(PHOTO_DIR, { recursive: true });

// Photos used by the design files outside the roster (Spencer leads the half-marathon goal page and the
// Exercise live-call mock; he is on shifu.health/about rather than the care-team carousel).
for (const f of ['coach-spencer.jpeg']) { copyFileSync(join(SITE_ROOT, 'assets', f), join(PHOTO_DIR, f)); shrink(join(PHOTO_DIR, f)); }
// Investor firm logos for the Manifesto page.
mkdirSync(join(HERE, 'assets/investors'), { recursive: true });
for (const f of ['launch.svg', 'z21-ventures.svg', 'teamworthy.svg']) copyFileSync(join(SITE_ROOT, 'assets/investors', f), join(HERE, 'assets/investors', f));

const people = Object.entries(overlay).map(([id, card]) => {
  const src = roster.get(id) || card.person;
  const livePhoto = src.photo.split('?')[0]; // "/assets/coach-x.png"
  const file = basename(livePhoto);
  if (src.photoLocal) {
    // placeholder or hand-supplied photo already in assets/team/ (people not on the live site yet)
  } else {
    copyFileSync(join(SITE_ROOT, livePhoto), join(PHOTO_DIR, file));
    shrink(join(PHOTO_DIR, file));
  }
  return {
    id,
    kind: card.kind,
    name: src.name,
    cred: card.cred,
    cardCred: src.cardCred ?? '',
    role: src.role ?? '',
    states: card.states,
    bio: card.bio,
    specs: card.specs,
    img: '/assets/team/' + file, // root-absolute: pages are served from clean routes like /nutrition/
    liveImg: src.photoLocal ? '' : LIVE_ORIGIN + livePhoto,
    profileUrl: LIVE_ORIGIN + '/team/' + id + '/',
    background: card.background ?? src.background ?? [], // overlay override: keep the text to the job they do here
    education: src.education ?? [],
    credentials: src.credentials ?? [],
    links: src.links ?? {},
    dietitian: !!src.dietitian,
    licensedStates: src.licensedStates ?? [],
    advisorRole: card.advisorRole ?? src.advisorRole ?? '',
    funFact: src.funFact ?? '',
    disclaimer: src.disclaimer ?? '',
  };
});

let out = `/* GENERATED by gen-team.mjs - do not edit by hand.
   Card fields come from team-overlay.json; name, photo, bio, education, credentials, licensing
   and links are pulled verbatim from ~/shifu-website/public/team/team-data.js.
   kind: "n" nutrition - "e" exercise - "a" clinical advisor (does not see members directly) - "f" founding team - "i" investor
   specs must match the Coverage page topic labels exactly.
   img is the self-hosted copy in assets/team/; liveImg and profileUrl point at shifu.health. */
window.SHIFU_SITE_TEAM = [
`;
for (const kind of ORDER) {
  out += `  /* ---------- ${HEADING[kind]} ---------- */\n`;
  for (const p of people.filter((x) => x.kind === kind)) {
    out += '  ' + JSON.stringify(p, null, 2).split('\n').join('\n  ') + ',\n';
  }
}
out += '];\n';

writeFileSync(join(HERE, 'shifu-team.js'), out);
// same roster as plain JSON, so the static build can generate profile pages from it
writeFileSync(join(HERE, 'team.json'), JSON.stringify(people, null, 2) + '\n');
console.log(`wrote shifu-team.js + team.json + ${people.length} photos in assets/team/ (` +
  ORDER.map((k) => `${k}=${people.filter((x) => x.kind === k).length}`).join(' ') + ')');
