/* GENERATED by gen-team.mjs - do not edit by hand.
   Card fields come from team-overlay.json; name, photo, bio, education, credentials, licensing
   and links are pulled verbatim from ~/shifu-website/public/team/team-data.js.
   kind: "n" nutrition - "e" exercise - "a" clinical advisor (does not see members directly)
   specs must match the Coverage page topic labels exactly.
   img is the self-hosted copy in assets/team/; liveImg and profileUrl point at shifu.health. */
window.SHIFU_SITE_TEAM = [
  /* ---------- Nutrition ---------- */
  {
    "id": "isabel-zimmermann",
    "kind": "n",
    "name": "Isabel Zimmermann, MS, RD, LD",
    "cred": "Registered Dietitian · MS Nutrition Sciences · sports nutrition",
    "cardCred": "Registered Dietitian",
    "role": "Registered Dietitian",
    "states": "Registered Dietitian (RD)",
    "bio": "Sports nutrition dietitian with nearly a decade of experience, most recently the primary sports dietitian at the University of Mississippi. A former Division I cross country and track athlete at NC State.",
    "specs": [
      "Race fueling",
      "Muscle gain",
      "Hydration",
      "Weight loss",
      "Meal prep",
      "Body recomposition"
    ],
    "img": "assets/team/coach-isabel.png",
    "liveImg": "https://shifu.health/assets/coach-isabel.png",
    "profileUrl": "https://shifu.health/team/isabel-zimmermann/",
    "background": [
      "A sports nutrition dietitian with nearly a decade of experience, Isabel has worked with everyday clients and elite athletes alike, combining performance, health, and sustainability. Most recently, she served as the primary sports nutrition dietitian at the University of Mississippi, supporting rifle, volleyball, tennis, and golf with individualized fueling strategies for performance and recovery. There, she collaborated with strength and conditioning, athletic training, and coaching staff to deliver integrated, athlete-centered care, ran individualized consultations and team education sessions, developed personalized meal guides, and performed hydration testing along with DEXA scan and lab value interpretation.",
      "Isabel completed her dietetic training through a series of rotations across North Carolina. At UNC Health Rex, she finished a 12-week clinical rotation at a 660-bed hospital, caring for renal, diabetes, cardiac, oncology, gastrointestinal, bariatric, and neurology patients using Epic EMR, alongside a food service rotation. Additional internships sharpened her focus on sports and community nutrition: athlete counseling and runner-fueling education at The Endurance Edge (where she wore a CGM to better understand patient experiences), outpatient and cardiac rehab counseling at Rex Wellness Centers, and SNAP education and outreach with the NC Department of Health and Human Services.",
      "A former Division I cross country and track athlete at NC State on a national championship-winning team, Isabel now races toward a sub-3-hour marathon, bringing the same performance mindset to the athletes and clients she supports."
    ],
    "education": [
      "Bachelors of Science: Applied Nutrition, NC State",
      "MS: Nutrition Sciences, Meredith College"
    ],
    "credentials": [
      "Registered Dietitian (RD) - Academy of Nutrition and Dietetics"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/isabelzimmermann/"
    },
    "dietitian": true,
    "licensedStates": [],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "kristina-bauer",
    "kind": "n",
    "name": "Kristina Bauer, MS, RDN, LD",
    "cred": "Registered Dietitian Nutritionist · MS · pediatric weight management",
    "cardCred": "Registered Dietitian",
    "role": "Registered Dietitian",
    "states": "Licensed: OH · KY",
    "bio": "Registered dietitian specializing in pediatric weight management at Cincinnati Children's. Works from Health at Every Size and intuitive eating rather than restrictive dieting.",
    "specs": [
      "Weight loss",
      "Cutting sugar",
      "Meal prep",
      "Eating well on a budget",
      "Plateaus"
    ],
    "img": "assets/team/coach-kristina.png",
    "liveImg": "https://shifu.health/assets/coach-kristina.png",
    "profileUrl": "https://shifu.health/team/kristina-bauer/",
    "background": [
      "Kristina is a registered dietitian specializing in pediatric weight management at Cincinnati Children's Hospital Medical Center, where she works with the Healthworks! program. Her approach centers on meeting patients where they are, supporting healthy eating, fostering a positive relationship with food, and promoting Health at Every Size (HAES) and intuitive eating rather than restrictive dieting. She is licensed in both Ohio and Kentucky and sees families across Greater Cincinnati clinic locations.",
      "She completed her dietetic internship rotations at Cincinnati Children's, Twin Towers Senior Living Community, Norwood City Schools / Milford School System, and Children's Hunger Alliance, building experience across clinical, school, senior living, and community nutrition settings. Earlier at the University of Cincinnati she supported collegiate athletes through Bearcat's Fuel Station, preparing individualized pre- and post-game nutrition and creating athlete nutrition content during COVID-19, and served as a teaching assistant and peer leader for first-year students.",
      "Kristina holds a Master of Science in Dietetics and a Bachelor of Science in Dietetics from the University of Cincinnati, with a minor in psychology. She is passionate about helping children and adolescents build sustainable habits that support long-term well-being."
    ],
    "education": [
      "Bachelors of Science: Dietetics, University of Cincinnati",
      "MS: Dietetics, University of Cincinnati"
    ],
    "credentials": [
      "Registered Dietitian Nutritionist (RDN)",
      "Licensed Dietitian (LD), Ohio and Kentucky"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/kristina-bauer5"
    },
    "dietitian": true,
    "licensedStates": [
      "Ohio",
      "Kentucky"
    ],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "brooke-caplinger",
    "kind": "n",
    "name": "Brooke Caplinger, MS, RDN, LDN, CPT",
    "cred": "Registered Dietitian Nutritionist · Certified Personal Trainer",
    "cardCred": "Registered Dietitian + Certified Personal Trainer",
    "role": "Registered Dietitian",
    "states": "Licensed: MA",
    "bio": "Registered dietitian and personal trainer of six years who pairs nutrition coaching with exercise guidance. Works in K-12 school nutrition and provides insurance-covered coaching through Kickoff.",
    "specs": [
      "Weight loss",
      "Body recomposition",
      "Muscle gain",
      "Meal prep",
      "Beginner lifting"
    ],
    "img": "assets/team/coach-brooke.png",
    "liveImg": "https://shifu.health/assets/coach-brooke.png",
    "profileUrl": "https://shifu.health/team/brooke-caplinger/",
    "background": [
      "Brooke is a registered dietitian working in K-12 school nutrition with Chartwells School Dining Services, where she supports healthier school food environments and student nutrition. In parallel, she practices as a Registered Dietitian with Kickoff, providing insurance-covered nutrition coaching alongside personalized exercise guidance.",
      "Alongside dietetics, she has been a personal trainer for six years and is passionate about helping people build healthier, more sustainable routines through both nutrition and exercise. She is based in Medford, Massachusetts, and holds RDN and LDN credentials.",
      "Brooke earned a Master of Science in Nutrition and Human Performance from Merrimack College and a Bachelor of Science in Health Promotion, Nutrition, and Exercise Science from The Ohio State University."
    ],
    "education": [
      "Bachelors of Science: Health Promotion, Nutrition, and Exercise Science, The Ohio State University",
      "MS: Nutrition and Human Performance, Merrimack College"
    ],
    "credentials": [
      "Registered Dietitian Nutritionist (RDN)",
      "Licensed Dietitian Nutritionist (LDN)",
      "Certified Personal Trainer (CPT)"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/bcaplinger"
    },
    "dietitian": true,
    "licensedStates": [
      "Massachusetts"
    ],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "nickie-patel",
    "kind": "n",
    "name": "Nickie Patel, RDN",
    "cred": "Registered Dietitian Nutritionist · metabolic & hormone health",
    "cardCred": "Registered Dietitian",
    "role": "Registered Dietitian",
    "states": "Licensed in 17 states",
    "bio": "Registered dietitian with a kinesiology background who focuses on weight loss that protects metabolism, hormone concerns such as PCOS and thyroid, and performance goals. Uses wearable data and bloodwork to guide plans.",
    "specs": [
      "GLP-1 guidance",
      "GLP-1 side effects",
      "Weight loss",
      "PCOS",
      "Plateaus",
      "Insulin resistance",
      "Body recomposition",
      "Meal prep"
    ],
    "img": "assets/team/coach-nickie.png",
    "liveImg": "https://shifu.health/assets/coach-nickie.png",
    "profileUrl": "https://shifu.health/team/nickie-patel/",
    "background": [
      "Nickie is a Registered Dietitian Nutritionist based in Miami, Florida, with a background in kinesiology and exercise science. She helps busy people optimize their health through personalized nutrition, habit coaching, and data-driven insights, with a focus on sustainable routines rather than crash diets or perfectionism.",
      "Most of her clients come to her for weight loss that protects metabolism, hormone-related concerns such as PCOS or thyroid issues, or performance goals across training, work, and daily life. She takes a whole-body, science-based approach that looks at food, movement, stress, sleep, and real-world habits, and uses tools like wearable data and bloodwork when available to guide more targeted changes.",
      "Nickie earned a Master of Science in Dietetics and Nutritional Science from Florida International University and a Bachelor of Science in Health and Exercise Science from the University of Oklahoma. She previously completed a sports nutrition internship at the University of Oklahoma and brings that performance mindset into how she coaches clients toward lasting habits."
    ],
    "education": [
      "Bachelors of Science: Health and Exercise Science, University of Oklahoma",
      "MS: Dietetics and Nutritional Science, Florida International University"
    ],
    "credentials": [
      "Registered Dietitian Nutritionist (RDN)",
      "Licensed Dietitian, Florida"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/nickie-patel-5bb14b194"
    },
    "dietitian": true,
    "licensedStates": [
      "Arizona",
      "California",
      "Colorado",
      "Connecticut",
      "Florida",
      "Hawaii",
      "Indiana",
      "Massachusetts",
      "Michigan",
      "New Jersey",
      "New York",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Texas",
      "Virginia",
      "Wisconsin"
    ],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "emily-levin",
    "kind": "n",
    "name": "Emily Levin, MPH, RDN",
    "cred": "Registered Dietitian Nutritionist · MPH",
    "cardCred": "Registered Dietitian",
    "role": "Registered Dietitian",
    "states": "Registered Dietitian Nutritionist (RDN)",
    "bio": "Registered dietitian and Public Health Advisor in the NIH Office of Nutrition Research. Brings a public-health lens to translating nutrition evidence into everyday practice.",
    "specs": [
      "Eating well on a budget",
      "Plant-based",
      "Meal prep",
      "Cholesterol",
      "Blood pressure"
    ],
    "img": "assets/team/coach-emily-levin.png",
    "liveImg": "https://shifu.health/assets/coach-emily-levin.png",
    "profileUrl": "https://shifu.health/team/emily-levin/",
    "background": [
      "Emily is a Registered Dietitian Nutritionist and Public Health Advisor in the NIH Office of Nutrition Research, where she helps advance national nutrition research priorities and cross-agency collaboration. Based in New York, she brings a public-health lens to how nutrition guidance is translated into practice.",
      "She has contributed to federal nutrition initiatives, including support work connected to the Dietary Guidelines process, and is active in Food is Medicine programming, including leadership around oncology care symposiums with partners like the American Cancer Society. Her work sits at the intersection of evidence, policy, and practical nutrition support.",
      "Emily holds a Master of Public Health and is a Registered Dietitian Nutritionist. She completed her graduate training through UTHealth Houston and brings that clinical and public-health foundation into how she supports clients and teams."
    ],
    "education": [
      "MPH: Public Health, UTHealth Houston"
    ],
    "credentials": [
      "Registered Dietitian Nutritionist (RDN)",
      "Master of Public Health (MPH)"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/emilyclevin/"
    },
    "dietitian": true,
    "licensedStates": [],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "ashley-art",
    "kind": "n",
    "name": "Ashley Art, MS, RDN, LD",
    "cred": "Registered Dietitian Nutritionist · MS · community & clinical",
    "cardCred": "Registered Dietitian",
    "role": "Registered Dietitian",
    "states": "Licensed: OH",
    "bio": "Registered dietitian at Lutheran Social Services of Central Ohio supporting community and clinical nutrition. Trained across WIC and rural healthcare settings, with a focus on guidance that fits real life.",
    "specs": [
      "Eating well on a budget",
      "Meal prep",
      "Cutting sugar",
      "Weight loss",
      "Hydration"
    ],
    "img": "assets/team/coach-ashley-art.png",
    "liveImg": "https://shifu.health/assets/coach-ashley-art.png",
    "profileUrl": "https://shifu.health/team/ashley-art/",
    "background": [
      "Ashley is a Registered Dietitian Nutritionist with a strong focus on helping clients reach their nutrition goals and improve quality of life through practical, motivating guidance. She currently practices as a Registered Dietitian at Lutheran Social Services of Central Ohio in Columbus, supporting community and clinical nutrition needs.",
      "Her training path includes dietetic internship experience across WIC, Appalachian Regional Healthcare System, and High Country Community Health, building a foundation in community and clinical care. She is passionate about connecting with clients, finding approaches that fit real life, and supporting sustainable behavior change.",
      "Ashley earned a Master of Science in Nutrition and Foods (Dietetics) from Appalachian State University and is licensed as a dietitian in Ohio."
    ],
    "education": [
      "MS: Nutrition and Foods, Dietetics, Appalachian State University"
    ],
    "credentials": [
      "Registered Dietitian Nutritionist (RDN)",
      "Licensed Dietitian (LD), Ohio"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/ashley-aguilar-ms-rdn-ld-50a7b0170"
    },
    "dietitian": true,
    "licensedStates": [
      "Ohio"
    ],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "michelle-wolff",
    "kind": "n",
    "name": "Michelle Wolff, RDN, CDN",
    "cred": "Registered Dietitian Nutritionist · CDN · relationship with food",
    "cardCred": "Registered Dietitian",
    "role": "Registered Dietitian",
    "states": "Licensed in 17 states",
    "bio": "Board-certified dietitian in New York City who helps clients rebuild trust with their bodies and their relationship with food. A former Division I cross country and track athlete, with continued training in functional nutrition.",
    "specs": [
      "Gut health",
      "IBS",
      "Reflux",
      "Cutting sugar",
      "Meal prep",
      "Eating out & travel",
      "Hydration"
    ],
    "img": "assets/team/coach-michelle-wolff.png",
    "liveImg": "https://shifu.health/assets/coach-michelle-wolff.png",
    "profileUrl": "https://shifu.health/team/michelle-wolff/",
    "background": [
      "Michelle is a board-certified Registered Dietitian Nutritionist and New York State Certified Dietitian-Nutritionist based in New York City. She helps clients rebuild trust with their bodies, explore their relationship with food, and learn how to nourish themselves with more confidence and less noise.",
      "She completed her undergraduate degree at the University of North Florida, where she competed in Division I Cross Country and Track, then moved to New York City for her Dietetic Internship. She has additional experience interning in rehabilitation settings and writing and editing for a nutrition news magazine, and continues training in functional nutrition.",
      "Michelle specializes in eating disorders, intuitive eating, and evidence-based counseling for a range of medical and wellness goals. Her approach is collaborative and realistic: start where you are, set sustainable goals, and build tools that make nutrition decisions feel clearer over time."
    ],
    "education": [
      "Bachelors: University of North Florida"
    ],
    "credentials": [
      "Registered Dietitian Nutritionist (RDN)",
      "Certified Dietitian-Nutritionist (CDN), New York"
    ],
    "links": {},
    "dietitian": true,
    "licensedStates": [
      "Arizona",
      "California",
      "Colorado",
      "Connecticut",
      "Hawaii",
      "Illinois",
      "Indiana",
      "Massachusetts",
      "Michigan",
      "New Jersey",
      "New York",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Texas",
      "Virginia",
      "Wisconsin"
    ],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "jessica-weissman",
    "kind": "n",
    "name": "Jessica Weissman, PhD, RDN, LDN, CPT",
    "cred": "Registered Dietitian Nutritionist · PhD · Certified Personal Trainer",
    "cardCred": "Registered Dietitian + Certified Personal Trainer",
    "role": "Registered Dietitian",
    "states": "Licensed: FL · IL",
    "bio": "Registered dietitian, personal trainer, and Department Chair of Integrative and Functional Nutrition at Saybrook University. More than a decade across bariatric, outpatient, hospital, and wellness settings.",
    "specs": [
      "GLP-1 guidance",
      "GLP-1 side effects",
      "Weight loss",
      "Type 2 diabetes",
      "Insulin resistance",
      "Body recomposition",
      "Plateaus",
      "Beginner lifting"
    ],
    "img": "assets/team/coach-jessica-weissman.png",
    "liveImg": "https://shifu.health/assets/coach-jessica-weissman.png",
    "profileUrl": "https://shifu.health/team/jessica-weissman/",
    "background": [
      "Jessica is a Registered Dietitian Nutritionist, Licensed Dietitian Nutritionist, and Certified Personal Trainer with more than a decade of clinical, academic, and fitness experience. She currently serves as Department Chair and Associate Professor of Integrative and Functional Nutrition at Saybrook University, where she leads a graduate program of more than 150 students, and practices as a Registered Dietitian with Vida Health.",
      "Her clinical background spans bariatric, outpatient, hospital, long-term care, and wellness settings, including work with NutraCo, Erickson Senior Living, Kindred Healthcare, Boca Raton Regional Hospital, Holy Cross Hospital, and nutrition counseling at Amrit Ocean Resort. She previously served as Program Director and Department Chair for Dietetics and Nutrition at Keiser University Melbourne, and has published and presented widely on nutrition, public health, and clinical practice.",
      "Jessica earned a PhD in Public Health from Florida International University, an MS in Dietetics and Nutrition from FIU's coordinated program, and a BSE in Exercise Science and Health Promotion from Florida Atlantic University. She became a registered and licensed dietitian in 2011 and is licensed in Florida and Illinois. She also holds a personal training credential through the National Federation of Professional Trainers."
    ],
    "education": [
      "BSE: Exercise Science and Health Promotion, Florida Atlantic University",
      "MS: Dietetics and Nutrition, Florida International University",
      "PhD: Public Health, Florida International University"
    ],
    "credentials": [
      "Registered Dietitian Nutritionist (RDN)",
      "Licensed Dietitian Nutritionist (LDN), Florida and Illinois",
      "Certified Personal Trainer (NFPT)"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/jessica-weissman-phd-rdn-ldn-cpt-9a87851b/"
    },
    "dietitian": true,
    "licensedStates": [
      "Florida",
      "Illinois"
    ],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "christopher-peterson",
    "kind": "n",
    "name": "Christopher Q. Peterson, MS, RDN",
    "cred": "Registered Dietitian Nutritionist · MS Nutrition Diagnostics · performance",
    "cardCred": "Registered Dietitian",
    "role": "Registered Dietitian",
    "states": "Registered Dietitian Nutritionist (RDN)",
    "bio": "Registered dietitian specializing in clinical and performance nutrition, previously a nutrition associate with the Detroit Tigers organization. Works on sports nutrition, weight management, and hormone-driven health.",
    "specs": [
      "Race fueling",
      "Muscle gain",
      "Weight loss",
      "Body recomposition",
      "Hydration",
      "Meal prep"
    ],
    "img": "assets/team/coach-christopher-peterson.png",
    "liveImg": "https://shifu.health/assets/coach-christopher-peterson.png",
    "profileUrl": "https://shifu.health/team/christopher-peterson/",
    "background": [
      "Christopher is a Registered Dietitian Nutritionist based in Aurora, Colorado, specializing in clinical and performance nutrition. He currently practices as a Registered Dietitian with Nourish, supporting clients on sports nutrition, weight management, and hormone-driven health, and consults as a performance dietitian with Foodzee Games.",
      "He previously served as a Nutrition Associate with the Detroit Tigers and their Triple-A affiliate, the Toledo Mud Hens, where he helped fuel professional athletes through tailored catering, hydration and recovery education, and close collaboration with athletic trainers and strength coaches. Earlier he practiced through ChrisP Nutrition Co. in Denver and as a Registered Dietitian with Foodsmart, and volunteered as a sports nutritionist at the Colorado School of Mines.",
      "Christopher earned a Master of Science in Nutrition Diagnostics from Cox College and became a Registered Dietitian in 2021. His work sits at the intersection of clinical care and athletic performance, helping people fuel training, manage weight, and build nutrition habits that last."
    ],
    "education": [
      "MS: Nutrition Diagnostics, Cox College"
    ],
    "credentials": [
      "Registered Dietitian Nutritionist (RDN)",
      "Master of Science (MS), Nutrition Diagnostics"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/christopher-peterson-ms-rdn-347555131/"
    },
    "dietitian": true,
    "licensedStates": [],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "nilufer-ece-bozkan",
    "kind": "n",
    "name": "Nilüfer Ece Bozkan",
    "cred": "Certified Nutritionist · Integrative Nutrition",
    "cardCred": "Certified Nutritionist",
    "role": "Health & Wellness Coach",
    "states": "General wellness · all states",
    "bio": "Runs Wellness with Nilufer, a remote one-on-one coaching practice built around sustainable habits and personalized wellness plans. Takes a whole-body approach across mental, physical, and everyday routines.",
    "specs": [
      "Meal prep",
      "Eating well on a budget",
      "Cutting sugar",
      "Hydration",
      "Plant-based",
      "Sleep & recovery"
    ],
    "img": "assets/team/coach-nilufer.png",
    "liveImg": "https://shifu.health/assets/coach-nilufer.png",
    "profileUrl": "https://shifu.health/team/nilufer-ece-bozkan/",
    "background": [
      "Since 2023, Nilüfer has run Wellness with Nilufer, a self-employed, remote coaching practice where she works one-on-one with clients to help them build sustainable habits, achievable goals, and personalized wellness plans. Her approach is whole-body and holistic, treating mental, physical, and spiritual health as interconnected and equally important to overall wellbeing. Through her practice she also offers a health and cooking blog and one-on-one coaching calls via her website.",
      "Her movement and group-instruction experience includes planning lessons for varied skill levels and adapting in real time, drawing on a working understanding of anatomy and physiology to give clear cues for safe movement and hands-on adjustments, and creating space for emotional regulation and mindfulness before, during, and after class, supported by strong verbal instruction and public-speaking skills."
    ],
    "education": [
      "Bachelors Degree: Psychology, Furman University"
    ],
    "credentials": [
      "Institute for Integrative Nutrition Certificate"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/nilufer-ece-bozkan4/"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "",
    "disclaimer": "Nilüfer Ece Bozkan is a certified health and wellness coach. Her work is in holistic wellness coaching, not licensed clinical care. She does not provide medical nutrition therapy, physical therapy, or any other clinical or medical service, and her coaching is intended to support general wellness rather than diagnose or treat any condition."
  },
  /* ---------- Exercise ---------- */
  {
    "id": "michaela-gleed",
    "kind": "e",
    "name": "Michaela Gleed",
    "cred": "NASM Certified Personal Trainer · Pilates · Yoga Alliance",
    "cardCred": "Certified Strength and Nutrition",
    "role": "Wellness & Movement Instructor",
    "states": "All states",
    "bio": "Founder and lead instructor of Habitual, blending the breath work of yoga, the control of Pilates, and the discipline of interval training into routines people keep.",
    "specs": [
      "Mobility",
      "Home workouts",
      "Busy-schedule programming",
      "Beginner lifting",
      "Sleep & recovery"
    ],
    "img": "assets/team/coach-michaela.png",
    "liveImg": "https://shifu.health/assets/coach-michaela.png",
    "profileUrl": "https://shifu.health/team/michaela-gleed/",
    "background": [
      "Since 2020, Michaela has been the Founder and Lead Instructor of Habitual, a self-employed venture in South Carolina where she blends the mindfulness and breath work of yoga, the technique and control of Pilates, and the strength and discipline of high-intensity interval training to help clients build sustainable wellness routines. In parallel, she works as a private yoga instructor, credentialed through Yoga Alliance, teaching one-on-one sessions focused on meditation, movement, and breath work, currently serving the Greenville and Spartanburg area.",
      "Her broader background spans operations, culinary, and fitness leadership. As Area Manager and Executive Chef at Southern Pressed Juicery (2022–2023), she oversaw two retail locations and a team of roughly 30, stepped into executive chef duties for four months (managing production, inventory, ordering, and menu development), ran in-store marketing events, and built front- and back-of-house operational systems to improve efficiency, grow sales, and reduce waste while managing labor and budget targets. She also worked as a Realtor with The Ponce Realty Group (2022–2023) and, earlier, as a personal trainer at 9Round Fitness (2019–2020)."
    ],
    "education": [],
    "credentials": [
      "Mat Level 1 Pilates",
      "Yoga Alliance",
      "NASM Certified Personal Trainer",
      "NASM Nutrition Certification"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/michaela-gleed-24b56116b/?skipRedirect=true"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "",
    "disclaimer": "Michaela Gleed is a wellness and movement instructor. Her work is in fitness and mindful movement coaching, not licensed clinical care. She does not provide medical nutrition therapy, physical therapy, or any other clinical or medical service, and her offerings are intended to support general wellness rather than diagnose or treat any condition."
  },
  {
    "id": "jerome-bacon-iii",
    "kind": "e",
    "name": "Jerome Bacon III, MS, ACSM-EP, NASM-CES",
    "cred": "ACSM Certified Exercise Physiologist · Corrective Exercise Specialist",
    "cardCred": "Certified Strength",
    "role": "Exercise Coach",
    "states": "All states",
    "bio": "Clinical exercise physiologist with more than two decades in cardiopulmonary rehabilitation. Builds ACSM-guided exercise prescriptions from medical records and teaches safe, self-monitored home training.",
    "specs": [
      "Hypertension-safe training",
      "Home workouts",
      "Beginner lifting",
      "Return from injury",
      "Busy-schedule programming"
    ],
    "img": "assets/team/coach-jerome.png",
    "liveImg": "https://shifu.health/assets/coach-jerome.png",
    "profileUrl": "https://shifu.health/team/jerome-bacon-iii/",
    "background": [
      "Jerome is a Clinical Exercise Physiologist and Lifestyle Coach at ECU Health Lifestyle Medicine in Greenville, North Carolina, with more than two decades of experience in cardiopulmonary rehabilitation and clinical exercise prescription. In his current roles he develops ACSM-guided exercise prescriptions from medical records, assesses patients for exercise appropriateness and limitations, monitors progression toward goals, and educates patients on safe self-monitored home exercise as part of a multidisciplinary rehab team.",
      "He previously served as an Exercise Physiologist at Cape Fear Valley Health System / HealthPlex of Cape Fear Valley, delivering cardiopulmonary outpatient care focused on risk-factor management through supervised exercise therapy. A former East Carolina University football student-athlete (1998–2003), he brings lived athletic experience into how he coaches patients through recovery and lifestyle change.",
      "Jerome holds a Master of Science in Exercise Physiology from East Carolina University and maintains ACSM Exercise Physiologist (ACSM-EP) and NASM Corrective Exercise Specialist (NASM-CES) credentials."
    ],
    "education": [
      "MS: Exercise Physiology, East Carolina University"
    ],
    "credentials": [
      "ACSM Certified Exercise Physiologist (ACSM-EP)",
      "NASM Corrective Exercise Specialist (NASM-CES)"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/jerome-bacon"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "libby-thompson",
    "kind": "e",
    "name": "Libby Thompson",
    "cred": "Exercise Physiologist · NASM Certified",
    "cardCred": "Certified Strength",
    "role": "Exercise Physiologist",
    "states": "All states",
    "bio": "Exercise physiologist who began in cardiology before spending three years in an obesity management clinic at Cincinnati Children's, helping patients and families build healthier routines.",
    "specs": [
      "Beginner lifting",
      "Home workouts",
      "Hypertension-safe training",
      "Busy-schedule programming",
      "Mobility"
    ],
    "img": "assets/team/coach-libby.png",
    "liveImg": "https://shifu.health/assets/coach-libby.png",
    "profileUrl": "https://shifu.health/team/libby-thompson/",
    "background": [
      "Libby currently lives in Columbus, Ohio, but spent the past four years in Cincinnati, Ohio. She began her career as an Exercise Physiologist in Cardiology at The Christ Hospital before joining Cincinnati Children's Hospital, where she spent three years working in an obesity management clinic. During her time at Cincinnati Children's, she earned her Master of Science in Health Administration (MSHA) from Northern Kentucky University while continuing to work.",
      "Her position there was focused on helping patients and families build healthier lifestyles, and she also taught free exercise classes for children in the community. Most recently, she transitioned into a Marketing and Community Relations role with a pediatric dental organization. Her role is community outreach, partnership development, event planning, and patient engagement. She enjoys connecting with people and helping organizations make a meaningful impact in the communities they serve."
    ],
    "education": [
      "Bachelors of Science: Exercise Science, Bowling Green State University",
      "MSHA: Health Administration, Northern Kentucky University"
    ],
    "credentials": [
      "NASM Certified",
      "Exercise Physiologist, Cincinnati Children's Hospital"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/libby-thompson-03366122b/"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "",
    "disclaimer": ""
  },
  {
    "id": "taylor-duckett",
    "kind": "e",
    "name": "Taylor Duckett",
    "cred": "NASM Certified Strength Coach · Personal Trainer",
    "cardCred": "Certified Strength",
    "role": "Personal Trainer + Certified Strength Coach",
    "states": "All states",
    "bio": "Personal trainer and strength coach who has worked with hundreds of clients across every age and fitness level since 2015, and now coaches online as well as in person.",
    "specs": [
      "Building strength",
      "Beginner lifting",
      "Home workouts",
      "Busy-schedule programming",
      "Body recomposition"
    ],
    "img": "assets/team/coach-taylor.png",
    "liveImg": "https://shifu.health/assets/coach-taylor.png",
    "profileUrl": "https://shifu.health/team/taylor-duckett/",
    "background": [
      "Taylor is a personal trainer and fitness coach who turned her passion for health and fitness into a career. In 2015, halfway through her nursing program, she realized that path wasn't for her. Having always loved being active and being around people, she began personal training and teaching group exercise classes in college. Since then, she has worked with hundreds of clients of all ages and fitness levels to help them achieve their goals. She has recently expanded into online coaching, embracing the opportunity to reach and support people well beyond her local area.",
      "Taylor lives in South Carolina with her husband Sam and their two dogs, Luna and Tywin. When she's not coaching, she can be found training for her own races, enjoying espresso martinis with friends, or going to concerts."
    ],
    "education": [
      "East Carolina University"
    ],
    "credentials": [
      "Certified NASM Strength Coach"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/ACoAABcmqrUBtZVvrXhfrok5YLgmhsbpv7bws_w?skipRedirect=true&miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABcmqrUBtZVvrXhfrok5YLgmhsbpv7bws_w"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "Certified Strength Coach.",
    "disclaimer": ""
  },
  {
    "id": "katie-callo",
    "kind": "e",
    "name": "Katie Callo",
    "cred": "ISSA Certified Personal Trainer · Pilates · Guinness World Record holder",
    "cardCred": "Certified Personal Trainer + World Record Holder",
    "role": "Personal Trainer",
    "states": "All states",
    "bio": "Certified personal trainer and Pilates instructor with UCLA Recreation's FITWELL program, and a Guinness World Record holder for the heaviest female hip thrust. Also a certified Diabetes Prevention Program coach.",
    "specs": [
      "Building strength",
      "Muscle gain",
      "Mobility",
      "Return from injury",
      "Type 2 diabetes",
      "Prediabetes & A1c"
    ],
    "img": "assets/team/coach-katie-callo.png",
    "liveImg": "https://shifu.health/assets/coach-katie-callo.png",
    "profileUrl": "https://shifu.health/team/katie-callo/",
    "background": [
      "Katie is a certified personal trainer, group fitness instructor, and Pilates instructor with UCLA Recreation's FITWELL program in Los Angeles, and a Guinness World Record holder for the heaviest weighted hip thrust by a female (605 lbs). She leads GroupX classes that combine mat Pilates with total-body strength and conditioning, supports Workstrong candidates through virtual and in-person rehab and cross-training, and builds personalized programs for goals like weight loss, strength, hypertrophy, and cardiovascular health.",
      "She is a Certified Personal Trainer and Certified Pilates Instructor through the International Sports Sciences Association (ISSA), and a Certified Diabetes Prevention Program coach through UCLA Health. Alongside coaching, she is Co-Founder of Refuel and previously served as President of CruX UCLA, UCLA's student neurotechnology organization, where she now remains an executive advisor.",
      "Katie earned a Bachelor of Science in Computational Psychology and Human-Centered Artificial Intelligence from UCLA. Her coaching style sits at the intersection of performance, movement quality, and practical habit building."
    ],
    "education": [
      "Bachelors of Science: Computational Psychology and Human-Centered Artificial Intelligence, UCLA"
    ],
    "credentials": [
      "Guinness World Record: Heaviest Weighted Hip Thrust (Female), 605 lbs",
      "ISSA Certified Personal Trainer",
      "ISSA Certified Pilates Instructor",
      "UCLA Health Diabetes Prevention Program Coach"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/kaitlyncallo/"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "",
    "disclaimer": "Katie Callo is a certified personal trainer and fitness instructor. Her work is in fitness coaching, not licensed clinical care. She does not provide medical nutrition therapy, physical therapy, or any other clinical or medical service, and her offerings are intended to support general wellness rather than diagnose or treat any condition."
  },
  {
    "id": "michael-hawkins",
    "kind": "e",
    "name": "Michael Hawkins",
    "cred": "ISSA Certified Strength Coach",
    "cardCred": "Certified Strength Coach",
    "role": "Certified Strength Coach",
    "states": "All states",
    "bio": "Certified strength coach with more than 25 years of dual experience in business and fitness, coaching people who have to fit training around a demanding schedule.",
    "specs": [
      "Building strength",
      "Busy-schedule programming",
      "Beginner lifting",
      "Home workouts",
      "Muscle gain"
    ],
    "img": "assets/team/coach-michael.png",
    "liveImg": "https://shifu.health/assets/coach-michael.png",
    "profileUrl": "https://shifu.health/team/michael-hawkins/",
    "background": [
      "Michael brings over 25 years of dual experience in business development and fitness. Professionally, he specializes in equipment financing for the construction sector, having served as a Business Development Officer, Territory Manager, and Regional Sales Manager. In these roles, he partners with equipment dealers to streamline the financing process for their customers, emphasizing fast credit decisions, broad credit approvals, and ease of execution. His work is driven by a commitment to fostering strong client relationships and leveraging expertise in business relationship management and leadership, empowering dealers and their customers with tailored financial solutions that enable growth in the competitive construction industry.",
      "Alongside his business career, Michael has maintained a 25-year commitment to fitness and overall wellness, supported by consistent training and deep knowledge of exercise techniques. He holds a Personal Training Certification through ISSA, with experience spanning strength training, conditioning, and developing structured fitness routines tailored to specific goals. He emphasizes discipline, proper form, and injury prevention, a background that has strengthened his work ethic, resilience, and ability to perform effectively in challenging environments."
    ],
    "education": [
      "New England College"
    ],
    "credentials": [
      "ISSA Certification"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/michael-hawkins-070709b8/"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "",
    "disclaimer": ""
  },
  /* ---------- Clinical advisors (internal consultants, not bookable) ---------- */
  {
    "id": "aaron-snyder",
    "kind": "a",
    "name": "Aaron Snyder",
    "cred": "Doctor of Physical Therapy · Orthopedic Clinical Specialist (OCS)",
    "cardCred": "Physical Therapist",
    "role": "Physical Therapist",
    "states": "Advisor · does not see members directly",
    "bio": "Orthopedic physical therapist and Head of Basketball Performance at Agile Physical Therapy, and a former professional point guard. Advises on physical therapy.",
    "specs": [
      "Return from injury",
      "Mobility",
      "Running injuries"
    ],
    "img": "assets/team/coach-aaron.jpg",
    "liveImg": "https://shifu.health/assets/coach-aaron.jpg",
    "profileUrl": "https://shifu.health/team/aaron-snyder/",
    "background": [
      "Aaron is a physical therapist who blends orthopedic clinical expertise with elite basketball experience. He has been at Agile Physical Therapy in San Carlos, California since 2021, where he practices as a physical therapist, completed an orthopedic physical therapy residency, and currently serves as Head of Basketball Performance (2024–present). He holds a Doctor of Physical Therapy from the UCSF/SFSU joint program and is board-certified in orthopedics (OCS), with a clinical skill set spanning manual therapy, rehabilitation, and SOAP-note documentation. Before Agile, he practiced as a physical therapist at Select Medical in Mill Valley.",
      "His connection to basketball runs throughout his career. Aaron played professionally as a point guard/shooting guard from 2013 to 2017, including two seasons with CB Cellera in Girona, Spain (13 ppg, 2 rpg, 3 apg), along with stints at the European Basketball Academy and the ABA's IE Invaders. He has paired that playing background with coaching since 2015, providing individual and group basketball skills training to players of all levels, in person and online, through CoachUp.",
      "His earlier experience built the foundation for this performance-and-rehab focus: a lead aide role at Rausch Physical Therapy & Sports Performance and an exercise specialist position where he coached clients on exercise mechanics, injury prevention, and individualized training. Today he sits at the intersection of physical therapy and basketball performance, drawing on lived experience as a professional athlete to inform how he rehabilitates and trains the players he works with."
    ],
    "education": [
      "DPT: Doctor of Physical Therapy, UCSF/SFSU",
      "Bachelors of Science: Kinesiology and Exercise Sciences, La Sierra University"
    ],
    "credentials": [
      "Orthopedic Clinical Specialist (OCS)",
      "Doctor of Physical Therapy, State of California"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/aaron-snyder-pt-dpt-ocs-apc-b042253a/"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "Advisor focused on training and supervising our AI Health Assistant in physical therapy.",
    "disclaimer": "Aaron acts as an internal consultant and does not actively see customers."
  },
  {
    "id": "eric-lee",
    "kind": "a",
    "name": "Eric Lee, DPT, CSCS",
    "cred": "Doctor of Physical Therapy · CSCS · Certified Dry Needling",
    "cardCred": "Physical Therapist",
    "role": "Sports Performance Physical Therapist",
    "states": "Advisor · does not see members directly",
    "bio": "Doctor of physical therapy and strength and conditioning specialist who founded ELee Performance PT in Miami, with experience across NCAA, MLB, and NFL athletes. Advises on sports performance and rehab.",
    "specs": [
      "Return from injury",
      "Running injuries",
      "Mobility",
      "Building strength"
    ],
    "img": "assets/team/coach-eric.png",
    "liveImg": "https://shifu.health/assets/coach-eric.png",
    "profileUrl": "https://shifu.health/team/eric-lee/",
    "background": [
      "Eric is a Doctor of Physical Therapy and Certified Strength and Conditioning Specialist based in Miami, where he founded ELee Performance PT to deliver one-on-one, concierge-level rehab and performance care. His practice bridges rehabilitation and strength training so athletes and active adults can recover from injury and return stronger, with plans built around the individual rather than rushed clinic throughput.",
      "His experience spans NCAA athletics, MLB, NFL, and elite private clinics. He has led athlete recovery programs, collaborated with sports scientists, and supported more than 200 collegiate athletes across football, lacrosse, baseball, and track and field, drawing on tools like ForceDecks and NordBord alongside dry needling and movement reconditioning. Earlier roles include strength and conditioning work with Stanford University Men's Lacrosse, a strength and conditioning internship with UCLA Football, and clinical work with athletes in the West LA College athletic training room. He has also practiced as an orthopedic and sport performance specialist at ASR Sports Medicine in Brickell.",
      "Eric earned his Doctor of Physical Therapy from the University of Southern California and a B.S. in Human Biology with an emphasis in Human Performance and Sports Medicine from Stanford University, where he competed in lacrosse. He holds CSCS credentials from the NSCA and is certified in dry needling (Cert. DN)."
    ],
    "education": [
      "Bachelors of Science: Human Biology (Human Performance and Sports Medicine), Stanford University",
      "DPT: Doctor of Physical Therapy, University of Southern California"
    ],
    "credentials": [
      "Doctor of Physical Therapy",
      "Certified Strength and Conditioning Specialist (CSCS), NSCA",
      "Certified Dry Needling (Cert. DN)"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/elee209/"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "Advisor focused on training and supervising our AI Health Assistant in physical therapy.",
    "disclaimer": "Eric acts as an internal consultant and does not actively see customers."
  },
  {
    "id": "hannah-todd",
    "kind": "a",
    "name": "Hannah Todd, DPT",
    "cred": "Doctor of Physical Therapy · Pelvic Health",
    "cardCred": "Physical Therapist",
    "role": "Pelvic Health Physical Therapist",
    "states": "Advisor · does not see members directly",
    "bio": "Doctor of physical therapy and founder of Vital Core Physical Therapy, treating pelvic floor dysfunction through in-person, virtual, and hybrid care. Advises on pelvic and postpartum health.",
    "specs": [
      "Pregnancy & postpartum",
      "Mobility",
      "Return from injury"
    ],
    "img": "assets/team/coach-hannah.png",
    "liveImg": "https://shifu.health/assets/coach-hannah.png",
    "profileUrl": "https://shifu.health/team/hannah-todd/",
    "background": [
      "Hannah is a Doctor of Physical Therapy and the founder of Vital Core Physical Therapy in Virginia Beach, where she treats people of all ages and genders for pelvic floor dysfunction and related conditions, offering in-person, virtual, and hybrid care. Her clinical focus includes bowel and bladder dysfunction, pelvic pain, pre- and postpartum care, post-surgical rehabilitation, and dry needling, delivered through an evidence-based, trauma-informed approach.",
      "Before founding Vital Core, she practiced as a pelvic health physical therapist at Direct Performance Physical Therapy, ODU Monarch Therapy, and Oxford Physical Therapy Centers. Outside clinic work, she serves as adjunct faculty at Old Dominion University, teaching DPT and undergraduate students on health equity, compassionate care, and therapeutic alliance, and she is an APTA Credentialed Clinical Instructor.",
      "In 2025 she co-authored Psychosocial Aspects of Rehabilitation: Enhancing Outcomes Through Compassionate Practice (Cognella), a textbook covering social determinants of health, trauma-informed care, motivational interviewing, and bias reduction for rehabilitation education. She holds a Doctor of Physical Therapy from Old Dominion University."
    ],
    "education": [
      "DPT: Doctor of Physical Therapy, Old Dominion University"
    ],
    "credentials": [
      "Doctor of Physical Therapy",
      "APTA Credentialed Clinical Instructor",
      "Pelvic health physical therapy"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/hannah-todd-0272b48a"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "Advisor focused on training and supervising our AI Health Assistant in physical therapy.",
    "disclaimer": "Hannah acts as an internal consultant and does not actively see customers."
  },
  {
    "id": "dena-kranzberg",
    "kind": "a",
    "name": "Dena Kranzberg, WHNP-BC",
    "cred": "Women's Health Nurse Practitioner (WHNP-BC) · NASM CPT · IFBB Pro",
    "cardCred": "Women's Health Nurse Practitioner",
    "role": "Nurse Practitioner",
    "states": "Advisor · does not see members directly",
    "bio": "Board-certified women's health nurse practitioner working in precision medicine and healthy longevity, with prior practice in perimenopause and menopause care. Advises on clinical nursing and women's health.",
    "specs": [
      "Menopause",
      "Pregnancy & postpartum",
      "PCOS"
    ],
    "img": "assets/team/coach-dena.png",
    "liveImg": "https://shifu.health/assets/coach-dena.png",
    "profileUrl": "https://shifu.health/team/dena-kranzberg/",
    "background": [
      "Dena is a board-certified Women's Health Nurse Practitioner with more than a decade of clinical and leadership experience across reproductive health, pandemic response, and precision medicine. She currently serves as Precision Nurse Practitioner and Administrative Lead at the Comite Center for Precision Medicine & Healthy Longevity in New York, and previously practiced as a Nurse Practitioner at Midi Health, a virtual clinic focused on perimenopause and menopause care.",
      "Earlier in her career she held senior clinical and training roles at Planned Parenthood of Greater New York, including Director of Clinical Training after the statewide affiliate merger, where she trained clinicians across dozens of health centers, led telehealth launch work during COVID-19, and provided advanced practice care including contraception, STI care, and complex LARC procedures. She also served as an NP across NYC Health + Hospitals and DocGo pandemic response programs covering COVID-19, Mpox, influenza, and migrant health testing and treatment, and has long taught group exercise while maintaining NASM personal training credentials and IFBB Pro status.",
      "Her academic path spans a Doctor of Nursing Practice in Executive Leadership from the University of Pennsylvania, an MS as a Women's Health Nurse Practitioner from Columbia University, a BSN from Johns Hopkins University, and a BA in Human Biology from Indiana University Bloomington. She has also served as a Clinical Instructor at Columbia University School of Nursing."
    ],
    "education": [
      "BA: Human Biology, Indiana University Bloomington",
      "BSN: Nursing, Johns Hopkins University",
      "MS: Women's Health Nurse Practitioner, Columbia University",
      "DNP: Executive Leadership, University of Pennsylvania"
    ],
    "credentials": [
      "Board-Certified Women's Health Nurse Practitioner (WHNP-BC)",
      "NASM Certified Personal Trainer",
      "IFBB Pro"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/dena-kranzberg"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "Advisor focused on clinical nursing and women's health expertise for our AI Health Assistant.",
    "disclaimer": "Dena acts as an internal consultant and does not actively see customers."
  },
  {
    "id": "grace-berger",
    "kind": "a",
    "name": "Grace Berger, LCSW",
    "cred": "Licensed Clinical Social Worker (LCSW) · CBT · DBT · ACT",
    "cardCred": "Clinical Social Worker / Therapist",
    "role": "Mental Health Therapist",
    "states": "Advisor · does not see members directly",
    "bio": "Licensed clinical social worker in Chicago providing outpatient psychotherapy for children, adolescents, and adults using CBT, DBT, and ACT. Advises on behavioral health.",
    "specs": [
      "Sleep & recovery"
    ],
    "img": "assets/team/coach-grace-berger.png",
    "liveImg": "https://shifu.health/assets/coach-grace-berger.png",
    "profileUrl": "https://shifu.health/team/grace-berger/",
    "background": [
      "Grace is a Licensed Clinical Social Worker based in Chicago, where she currently practices as a Mental Health Clinician at SHFT Behavioral Health. She provides outpatient psychotherapy, biopsychosocial and risk assessments, crisis intervention, and safety planning for children, adolescents, and adults, and coordinates care with families, schools, and healthcare partners.",
      "Her earlier clinical work includes program therapy at Silver Oaks Behavioral Hospital across PHP and IOP levels of care, child group therapy at Compass Health Center, and outpatient counseling with Innovative Counseling Partners. She also has a background in Applied Behavior Analysis, including work as a Registered Behavior Technician supporting neurodivergent children and families. That experience informs a structured, skills-based, and strengths-focused style of care.",
      "Grace's primary focus is children and adolescents, with regular parent sessions and family work alongside individual therapy. She also works with adults navigating life transitions and longer-standing mood concerns. Her therapeutic approaches include Cognitive Behavioral Therapy (CBT), Dialectical Behavior Therapy (DBT), and Acceptance and Commitment Therapy (ACT). She earned both her Bachelor of Arts and Master of Social Work from the University of Kentucky and is licensed as a clinical social worker in Illinois."
    ],
    "education": [
      "BA: Social Work, University of Kentucky",
      "MSW: Social Work, University of Kentucky"
    ],
    "credentials": [
      "Licensed Clinical Social Worker (LCSW), State of Illinois",
      "Cognitive Behavioral Therapy (CBT)",
      "Dialectical Behavior Therapy (DBT)",
      "Acceptance and Commitment Therapy (ACT)"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/grace-berger-lcsw-607a0a25a/"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "Advisor focused on therapy and behavioral health expertise for our AI Health Assistant.",
    "disclaimer": "Grace acts as an internal consultant and does not actively see customers."
  },
  {
    "id": "kiahlei-yaste",
    "kind": "a",
    "name": "Kiahlei Yaste",
    "cred": "Clinical Social Worker (SWC) · Mental Health Therapist",
    "cardCred": "Clinical Social Worker / Therapist",
    "role": "Mental Health Therapist",
    "states": "Advisor · does not see members directly",
    "bio": "Clinical social worker and mental health therapist in acute behavioral health, trained in motivational interviewing and trauma-informed care. Advises on therapy and behavioral health.",
    "specs": [
      "Sleep & recovery"
    ],
    "img": "assets/team/coach-kiahlei.png",
    "liveImg": "https://shifu.health/assets/coach-kiahlei.png",
    "profileUrl": "https://shifu.health/team/kiahlei-yaste/",
    "background": [
      "Kiahlei is a clinical social worker and mental health therapist based in Westminster, Colorado. She currently serves as a Mental Health Therapist at West Pines Behavioral Hospital, an acute behavioral health provider, where she delivers therapy services and contributes to interdisciplinary care for patients in higher-acuity settings.",
      "Her earlier clinical work includes roles as a Mental Health Clinician at Alis Behavioral Health and as a Clinician and KEEP Case Manager at Clarvida, where she managed caseloads, provided in-home therapy, and collaborated with youth and families. She brings training in Motivational Interviewing, trauma-informed care, and active listening, with a practice style rooted in attentive feedback and collaborative problem-solving.",
      "Kiahlei holds a Master of Social Work from the University of Denver and is licensed as a clinical social worker in Colorado (SWC). She has also completed the Colorado Family Support Assessment 2.0 credential through the Family Resource Center Association."
    ],
    "education": [
      "MSW: Social Work, University of Denver"
    ],
    "credentials": [
      "Clinical Social Worker (SWC), State of Colorado",
      "Colorado Family Support Assessment 2.0"
    ],
    "links": {
      "linkedin": "https://www.linkedin.com/in/kyaste"
    },
    "dietitian": false,
    "licensedStates": [],
    "advisorRole": "Advisor focused on therapy and behavioral health expertise for our AI Health Assistant.",
    "disclaimer": "Kiahlei acts as an internal consultant and does not actively see customers."
  },
];
